@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwiaWF0IjoxNTk1NDE0NjI5LCJleHAiOjE2MjY5NTA2Mjl9.X9-LqVWrNlgUISyCg4De3f0Bpm9o-AVQ6qLE0vu-yUM
@host = http://localhost:3000

###
GET {{host}}/customer/
Authorization: Bearer {{token}}

###
GET {{host}}/customer?_id=5f1834200ce15ea7d6b76021
Authorization: Bearer {{token}}

###
POST {{host}}/customer/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":"test1"
}

###
PUT {{host}}/customer
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "_id":"5f1834200ce15ea7d6b76021",
    "name":"Pizza"
}

###
DELETE {{host}}/customer/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id":"5f1aac8de4fff947e3c7cf30"
}